CONLL2003_INSTRUCT = "Please analyze the input sentence, identifying the type of entity for each word on a token-by-token basis. The entity types of interest include 'Person', 'Location', 'Organization', and 'Miscellaneous'.\nOutput format is: word_1(label_1), word_2(label_2), ...\nWe'll use the BIO-format to label the entities, where:\n1. B- (Begin) indicates the start of a named entity.\n2. I- (Inside) is used for words within a named entity but are not the first word.\n3. O (Outside) denotes words that are not part of a named entity.\n"

# AI_ET_INSTRUCT = "Please analyze the input sentence, and the mentioned entity in the sentence, identifying the type of the mentioned entity. The types of interest include 'country', 'field', 'metrics', 'researcher', 'organisation', 'algorithm', 'task', 'person', 'conference', 'university', 'location', 'misc', 'programlang', and 'product'.\nOutput format is: word_1(label_1), word_2(label_2), ...\nWe'll use the BIO-format to label the entities, where:\n1. B- (Begin) indicates the start of a named entity.\n2. I- (Inside) is used for words within a named entity but are not the first word.\n3. O (Outside) denotes words that are not part of a named entity.\n"
AI_ET_INSTRUCT = "Task: Identify the type of the specified entity in the given sentence.\n\nType set:\n- algorithm\n- conference\n- country\n- field\n- location\n- metrics\n- miscellaneous\n- organization\n- person\n- product\n- programming language\n- researcher\n- task\n- university\n- other (use only if none of the above types are suitable)\n\nInstructions:\n1. Read the sentence and mentioned entity carefully.\n2. Determine the most appropriate type for the entity based on the context and the provided type set.\n3. If none of the specific types fit, use 'other'.\n4. Respond with only the chosen type word. Do not explain or elaborate."

LITERATURE_ET_INSTRUCT = "Task: Identify the type of the specified entity in the given sentence.\n\nType set:\n- award\n- book\n- country\n- event\n- literary genre\n- location\n- magazine\n- miscellaneous\n- organization\n- person\n- poem\n- writer\n- other (use only if none of the above types are suitable)\n\nInstructions:\n1. Read the sentence and mentioned entity carefully.\n2. Determine the most appropriate type for the entity based on the context and the provided type set.\n3. If none of the specific types fit, use 'other'.\n4. Respond with only the chosen type word. Do not explain or elaborate."


MUSIC_ET_INSTRUCT = "Task: Identify the type of the specified entity in the given sentence.\n\nType set:\n- album\n- award\n- band\n- country\n- event\n- location\n- miscellaneous\n- musical artist\n- musical instrument\n- music genre\n- organization\n- person\n- song\n- other (use only if none of the above types are suitable)\n\nInstructions:\n1. Read the sentence and mentioned entity carefully.\n2. Determine the most appropriate type for the entity based on the context and the provided type set.\n3. If none of the specific types fit, use 'other'.\n4. Respond with only the chosen type word. Do not explain or elaborate."


POLITICS_ET_INSTRUCT = "Task: Identify the type of the specified entity in the given sentence.\n\nType set:\n- country\n- election\n- band\n- event\n- location\n- miscellaneous\n- organization\n- person\n- political party\n- politician\n- other (use only if none of the above types are suitable)\n\nInstructions:\n1. Read the sentence and mentioned entity carefully.\n2. Determine the most appropriate type for the entity based on the context and the provided type set.\n3. If none of the specific types fit, use 'other'.\n4. Respond with only the chosen type word. Do not explain or elaborate."

SCIENCE_ET_INSTRUCT = "Task: Identify the type of the specified entity in the given sentence.\n\nType set:\n- academic journal\n- astronomical object\n- award\n- chemical compound\n- chemical element\n- country\n- discipline\n- enzyme\n- event\n- location\n- miscellaneous\n- organization\n- person\n- protein\n- scientist\n- theory\n- university\n- other (use only if none of the above types are suitable)\n\nInstructions:\n1. Read the sentence and mentioned entity carefully.\n2. Determine the most appropriate type for the entity based on the context and the provided type set.\n3. If none of the specific types fit, use 'other'.\n4. Respond with only the chosen type word. Do not explain or elaborate."